language: node_js
node_js:
 - "4.1.2"
script: npm test
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
    - export NODE_PATH="/home/travis/build/ovakugit1/ReactTimer/node_modules"
cache:
  directories:
    - node_modules
