sudo: required
language: node_js
node_js:
 - "4.2"
script: npm test
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
    - sudo chown -R `whoami` ~/.npm
cache:
  directories:
    - node_modules
